#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/par2 ] ; then
wget --quiet -O /tmp/par2.tar.gz \
	https://ci.sparklyballs.com:9443/job/Application-Builds/job/par2-build/lastSuccessfulBuild/artifact/build/par2.tar.gz
tar xf \
	/tmp/par2.tar.gz -C /usr/bin/
ln -sf /usr/bin/par2 /usr/bin/par2create
ln -sf /usr/bin/par2 /usr/bin/par2repair
ln -sf /usr/bin/par2 /usr/bin/par2verify
rm -rf /tmp/par2.tar.gz
fi
